//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIGApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdEIGEntities : DbContext
    {
        public bdEIGEntities()
            : base("name=bdEIGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<FileCase> FileCases { get; set; }
        public virtual DbSet<FileJobApplication> FileJobApplications { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<OtherPerson> OtherPersons { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ScoreBusiness> ScoreBusinesses { get; set; }
        public virtual DbSet<ScoreOtherPerson> ScoreOtherPersons { get; set; }
        public virtual DbSet<ScorePerson> ScorePersons { get; set; }
        public virtual DbSet<ScoreProduct> ScoreProducts { get; set; }
        public virtual DbSet<Suggestion> Suggestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VisitBusiness> VisitBusinesses { get; set; }
        public virtual DbSet<VisitOtherPerson> VisitOtherPersons { get; set; }
        public virtual DbSet<VisitPerson> VisitPersons { get; set; }
        public virtual DbSet<VisitProduct> VisitProducts { get; set; }
    }
}
