//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIGApp.ORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEIGEntities : DbContext
    {
        public BDEIGEntities()
            : base("name=BDEIGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Business> Businesses { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<MediaBusiness> MediaBusinesses { get; set; }
        public virtual DbSet<MediaOtherPerson> MediaOtherPersons { get; set; }
        public virtual DbSet<MediaPerson> MediaPersons { get; set; }
        public virtual DbSet<MediaProduct> MediaProducts { get; set; }
        public virtual DbSet<MultimediaCase> MultimediaCases { get; set; }
        public virtual DbSet<MultimediaJobApplication> MultimediaJobApplications { get; set; }
        public virtual DbSet<OtherPerson> OtherPersons { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Suggestion> Suggestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
