//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIGApp.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Specialism { get; set; }
        public string SpecialismDescription { get; set; }
        public string WebPage { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Avatar { get; set; }
        public long IdPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
