//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIGApp.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MediaProducts = new HashSet<MediaProduct>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string TypeDescription { get; set; }
        public string AttendantName { get; set; }
        public string AttendantWebPage { get; set; }
        public string AttendantEmail { get; set; }
        public string AttendantPhone { get; set; }
        public float Latitude { get; set; }
        public float Longitude { get; set; }
        public string Date { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string CreationHourZone { get; set; }
        public string Avatar { get; set; }
        public string NameAvatar { get; set; }
        public long IdPackage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaProduct> MediaProducts { get; set; }
        public virtual Package Package { get; set; }
    }
}
